name: '22:10'
favicon: null
layout_spectrum: 0.6091159225907177
typography_spectrum: 0.6014919192530215
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.12728807097300887
  lightness: 0.8374701419379562
  saturation: 0.0037996259052306414
  rhythmicContrast: 0.66064990661107
purpose: []
